url: https://needleworm.github.io/
baseurl: /chatgpt

# Site settings
title: 챗GPT
email: bhban@kakao.com
description: 챗GPT - 마침내 찾아온 특이점

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/needleworm

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
