url: https://needleworm.github.io/
baseurl: /gpt2

# Site settings
title: 챗GPT
email: bhban@kakao.com
description: 챗GPT - GPT 노마드의 탄생생

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/needleworm

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
